### ISSUE TITLE
Prover definition generation fails for RV32

### ISSUE THREAD

**Issue by bauereiss** [CTSRD-CHERI/sail-cheri-riscv#11]
`cheri_prelude_64.sail` uses zero-length bitvectors, which some of the provers don't like.  For example, the Isabelle generation fails with a Lem `Type error: unbound type constructor: ty0`.  With a bit of refactoring, it should be possible to avoid `bits(0)`.

**Comment by marnovandermaas** [comment]
I see this is still the case. Do you still face the same issue in Isabelle? If so, we can think of a way to refactor.

**Comment by jrtc27** [comment]
Not being able to use common structures between the RV32 and RV64 code would be a real pain; doable but not good software engineering. This is therefore not a bug in sail-cheri-riscv; either get your theorem prover fixed or change Sail to work around this by eliding zero-length bit vectors in its output for the broken theorem provers.
