### ISSUE TITLE
Incorrect handling of compressed jumps instructions in cap mode

### ISSUE THREAD

**Issue by rmn30** [CTSRD-CHERI/sail-cheri-riscv#60]
It looks like the compressed versions of jump instructions never got updated to handle capability mode. I think the fix can be fairly easily implemented in [post decode hook](https://github.com/CTSRD-CHERI/sail-cheri-riscv/blob/62132ab372d52dde5055c42b92def1178ade5a1e/src/cheri_decode_ext.sail#L68). Just noting here for now until I have a chance to open a PR.

**Comment by jrtc27** [comment]
Compressed everything is missing because some of them don’t map as nicely with a post-decode hook (where we change the scale for loads/stores and whether 0 is valid)

**Comment by rmn30** [comment]
Do you mean replacing the floating point loads and stores with `clc` / `csc`? Aren't the other ones handled by the way the Sail executes the code for the expanded RISC-V instruction?

**Comment by PeterRugg** [comment]
Is this fixed by https://github.com/CTSRD-CHERI/sail-cheri-riscv/commit/1899944cf5167016b3bf4aba94d213b88f703d8e and friends?

**Comment by arichardson** [comment]
Yes this should be fixed now.
