### ISSUE TITLE
SRL is broken in 32-bit

### ISSUE THREAD

**Issue by marnovandermaas** [CTSRD-CHERI/sail-cheri-riscv#9]
In 32-bit SRL still considers shifting a 64-bit operation.

Implementation A is Sail and Implementation B is Spike.

Socket A Trace (model)
----------------------
	Trap: False, PCWD: 0x0000000080000004, RWD: 0x0000000000000718, MA: 0x0000000000000000, MWD: 0x0000000000000000, MWM: 0b00000000, I: 0x000000007181c193 (xori r3, r3, 1816)
	Trap: False, PCWD: 0x0000000080000008, RWD: 0xfffffffffe0ee000, MA: 0x0000000000000000, MWD: 0x0000000000000000, MWM: 0b00000000, I: 0x00000000fe0ee137 (lui r2, 1040622)
	Trap: False, PCWD: 0x000000008000000c, RWD: 0x0000000000000ed7, MA: 0x0000000000000000, MWD: 0x0000000000000000, MWM: 0b00000000, I: 0x000000007bf18293 (addi r5, r3, 1983)
	Trap: False, PCWD: 0x0000000080000010, RWD: 0x000001fffffffffc, MA: 0x0000000000000000, MWD: 0x0000000000000000, MWM: 0b00000000, I: 0x0000000000515133 (srl r2, r2, r5)
	halt token
Socket B Trace (implementation)
-------------------------------
	Trap: False, PCWD: 0xffffffff80000004, RWD: 0x0000000000000718, MA: 0x0000000000000000, MWD: 0x0000000000000000, MWM: 0b00000000, I: 0x000000007181c193 (xori r3, r3, 1816)
	Trap: False, PCWD: 0xffffffff80000008, RWD: 0xfffffffffe0ee000, MA: 0x0000000000000000, MWD: 0x0000000000000000, MWM: 0b00000000, I: 0xfffffffffe0ee137 (lui r2, 1040622)
	Trap: False, PCWD: 0xffffffff8000000c, RWD: 0x0000000000000ed7, MA: 0x0000000000000000, MWD: 0x0000000000000000, MWM: 0b00000000, I: 0x000000007bf18293 (addi r5, r3, 1983)
	Trap: False, PCWD: 0xffffffff80000010, RWD: 0x00000000000001fc, MA: 0x0000000000000000, MWD: 0x0000000000000000, MWM: 0b00000000, I: 0x0000000000515133 (srl r2, r2, r5)

*** Failed! Falsified (after 1 test):                  
.4byte 0x7181c193 # xori r3, r3, 1816
.4byte 0xfe0ee137 # lui r2, 1040622
.4byte 0x7bf18293 # addi r5, r3, 1983
.4byte 0x515133 # srl r2, r2, r5

**Comment by marnovandermaas** [comment]
Sorry this is a problem with TestRIG Makefile and/or sail-riscv so this should be closed.

**Comment by jrtc27** [comment]
Uh, never mind, thought this was spike for some reason.
